SELECT 
    PRODUCT.PRODUCT_CODE, (PRODUCT.PRICE * A.SA) AS SALES
FROM PRODUCT
JOIN (
    SELECT SUM(SALES_AMOUNT) AS SA, PRODUCT_ID
    FROM OFFLINE_SALE
    GROUP BY (PRODUCT_ID)
) AS A
ON PRODUCT.PRODUCT_ID = A.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE;
