SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
) A
ON AI.ANIMAL_ID = A.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY AI.ANIMAL_ID;