SELECT 
FP.PRODUCT_ID, 
FP.PRODUCT_NAME, 
(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;