SELECT 
    U.USER_ID,
    U.NICKNAME,
    A.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) A
ON U.USER_ID = A.WRITER_ID
WHERE A.PRICE >= 700000
ORDER BY A.PRICE;
