SELECT DISTINCT (CAR_RENTAL_COMPANY_CAR.CAR_ID) AS CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ON CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
WHERE 
    MONTH(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE) = '10' 
    AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;