SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
    GROUP BY CATEGORY
) A
ON FP.CATEGORY = A.CATEGORY
AND FP.PRICE = A.MAX_PRICE
ORDER BY MAX_PRICE DESC;
